### ISSUE TITLE
Login and Signup Form Handler not working as expected

### ISSUE THREAD

**Issue by the-nakki** [harryroshan/airline-ticket-reservation-system#1]
On clicking "Submit" during login or registration, the login_handler and new_user_form_handler show only blank pages. They do not redirect to user_reg_success or the homepage

**Comment by harryroshan** [comment]
Hi @the-nakki, first of all I'm very sorry for the late response, I have been busy lately.

Let's get into the issue. After clicking on "Submit" after entering the details in the registration page, the new_user_form_handler.php file adds all the data entered to the SQL database. It looks like it was unable to do so as it did not get redirected to homepage as you would have expected. The reason must be that the data could not be inserted correctly into the database.
This mostly is likely due to two reasons:-
1. The MySQL schema in `airline-ticket-reservation-system/MySQL Database file/airline_reservation.sql` was not imported (due to which the database was missing and caused errors).
2. The MySQL database connection file which is located at `airline-ticket-reservation-system/MySQL Database Connection file/mysqli_connect.php` needs to be moved to a level higher.
For e.g. if all the other PHP files are located at `C:\xampp\htdocs\atr`, the mysql_connect.php file should be moved one level higher to `C:\xampp\htdocs\mysqli_connect.php`. (This is where the file is expected to be located in the PHP files. The file location is one level higher due to security reasons IIRC). This is definitely a problem for others also who might clone this repo and needs to be fixed.

Also a quickstart page will definitely help others to get the website up and running quickly.

PS: You might want to set the `display_errors` variable in `php.ini` file to "on", so that you can take a look at the errors and debug yourself, otherwise the webpage will be blank and it will be difficult to debug. I got the following errors :- 
```

Warning: mysqli_stmt_bind_param() expects parameter 1 to be mysqli_stmt, boolean given in C:\xampp\htdocs\atr\new_user_form_handler.php on line 65

Warning: mysqli_stmt_execute() expects parameter 1 to be mysqli_stmt, boolean given in C:\xampp\htdocs\atr\new_user_form_handler.php on line 66

Warning: mysqli_stmt_affected_rows() expects parameter 1 to be mysqli_stmt, boolean given in C:\xampp\htdocs\atr\new_user_form_handler.php on line 67

Warning: mysqli_stmt_close() expects parameter 1 to be mysqli_stmt, boolean given in C:\xampp\htdocs\atr\new_user_form_handler.php on line 72
Submit Error
Warning: mysqli_error() expects exactly 1 parameter, 0 given in C:\xampp\htdocs\atr\new_user_form_handler.php on line 84
```

**Comment by the-nakki** [comment]
I fixed the problem by running the same thing in Windows. Most likely
mysql-server wasn't configured correctly. Thanks a lot for your help :)

Regards,
Nakul Suresh
